import io
import requests
from PIL import Image
from datetime import datetime
import streamlit as st
from google import genai
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
from src.helper import extract_text_from_pdf, ask_gemini
from src.job_api import fetch_linkedin_jobs, fetch_naukri_jobs

# --- Configure Gemini ---
genai.configure(api_key=st.secrets["GEMINI_API_KEY"])
model = genai.GenerativeModel("gemini-1.5-flash")

def ask_gemini(prompt: str, max_tokens: int = 500) -> str:
    """Send prompt to Gemini and return response text."""
    response = model.generate_content(
        prompt,
        generation_config=genai.types.GenerationConfig(
            temperature=0.5,
            max_output_tokens=max_tokens
        )
    )
    return response.text.strip()

# --- Helper: Fetch Company Logo ---
def fetch_logo(company_name: str) -> Image.Image | None:
    """Try to fetch a company logo using Clearbit Logo API (or similar)."""
    try:
        url = f"https://logo.clearbit.com/{company_name.lower().replace(' ', '')}.com"
        response = requests.get(url, timeout=5)
        if response.status_code == 200:
            return Image.open(io.BytesIO(response.content))
    except Exception:
        return None
    return None

# --- Helper: Add Page Number ---
def add_page_number(c, page_num: int):
    """Add page number at the bottom center of the page."""
    c.setFont("Helvetica", 9)
    c.drawString(letter[0] / 2 - 20, 20, f"Page {page_num}")

# --- PDF Export Function with Cover + TOC + Page Numbers ---
def create_pdf(user_name: str, summary: str, gaps: str, roadmap: str, linkedin_jobs: list, naukri_jobs: list) -> bytes:
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter

    # --- Cover Page ---
    today = datetime.today().strftime("%B %d, %Y")
    c.setFont("Helvetica-Bold", 24)
    c.drawCentredString(width / 2, height - 200, "Career Report")
    c.setFont("Helvetica", 16)
    c.drawCentredString(width / 2, height - 250, f"Prepared for {user_name}")
    c.setFont("Helvetica", 12)
    c.drawCentredString(width / 2, height - 280, f"Date: {today}")
    c.setFont("Helvetica-Oblique", 10)
    c.drawCentredString(width / 2, height - 320, "Generated by AI Job Recommender")
    add_page_number(c, 1)
    c.showPage()

    # --- Table of Contents Page ---
    c.setFont("Helvetica-Bold", 18)
    c.drawString(200, height - 80, "Career Report")
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height - 150, "Table of Contents")
    c.setFont("Helvetica", 12)
    toc_items = [
        ("📑 Resume Summary", "Page 3"),
        ("🛠️ Skill Gaps", "Page 3"),
        ("🚀 Future Roadmap", "Page 3"),
        ("💼 LinkedIn Jobs", "Page 4"),
        ("💼 Naukri Jobs", "Page 4"),
    ]
    y_pos = height - 180
    for section, page in toc_items:
        c.drawString(70, y_pos, f"{section} .......... {page}")
        y_pos -= 25
    add_page_number(c, 2)
    c.showPage()

    # --- Resume Summary, Skill Gaps, Roadmap ---
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, height - 50, "📑 Resume Summary")
    c.setFont("Helvetica", 10)
    text_obj = c.beginText(50, height - 70)
    for line in summary.split("\n"):
        text_obj.textLine(line)
    c.drawText(text_obj)

    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, height - 200, "🛠️ Skill Gaps")
    c.setFont("Helvetica", 10)
    text_obj = c.beginText(50, height - 220)
    for line in gaps.split("\n"):
        text_obj.textLine(line)
    c.drawText(text_obj)

    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, height - 350, "🚀 Future Roadmap")
    c.setFont("Helvetica", 10)
    text_obj = c.beginText(50, height - 370)
    for line in roadmap.split("\n"):
        text_obj.textLine(line)
    c.drawText(text_obj)
    add_page_number(c, 3)
    c.showPage()

    # --- LinkedIn Jobs ---
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, height - 50, "💼 Top LinkedIn Jobs")
    y_pos = height - 70
    for job in linkedin_jobs[:5]:
        logo = fetch_logo(job.get("companyName", ""))
        if logo:
            c.drawImage(ImageReader(logo), 50, y_pos - 30, width=40, height=40, preserveAspectRatio=True, mask='auto')
            x_offset = 100
        else:
            x_offset = 50
        job_text = f"{job.get('title')} at {job.get('companyName')} ({job.get('location')})"
        c.setFont("Helvetica", 10)
        c.drawString(x_offset, y_pos, job_text)
        if job.get("link"):
            c.linkURL(job["link"], (x_offset, y_pos - 2, x_offset + 400, y_pos + 12), relative=0)
        y_pos -= 60

    # --- Naukri Jobs ---
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y_pos - 20, "💼 Top Naukri Jobs (India)")
    y_pos -= 40
    for job in naukri_jobs[:5]:
        logo = fetch_logo(job.get("companyName", ""))
        if logo:
            c.drawImage(ImageReader(logo), 50, y_pos - 30, width=40, height=40, preserveAspectRatio=True, mask='auto')
            x_offset = 100
        else:
            x_offset = 50
        job_text = f"{job.get('title')} at {job.get('companyName')} ({job.get('location')})"
        c.setFont("Helvetica", 10)
        c.drawString(x_offset, y_pos, job_text)
        if job.get("url"):
            c.linkURL(job["url"], (x_offset, y_pos - 2, x_offset + 400, y_pos + 12), relative=0)
        y_pos -= 60

    add_page_number(c, 4)
    c.showPage()

    c.save()
    buffer.seek(0)
    return buffer.getvalue()

# --- Resume Analysis Workflow ---
uploaded_file = st.file_uploader("📤 Upload your resume (PDF)", type=["pdf"])
if uploaded_file and "resume_text" not in st.session_state:
    with st.spinner("🔍 Extracting text from your resume..."):
        st.session_state.resume_text = extract_text_from_pdf(uploaded_file)

    with st.spinner("📝 Summarizing your resume..."):
        st.session_state.summary = ask_gemini(
            f"Summarize this resume highlighting the skills, education, and experience:\n\n{st.session_state.resume_text}",
            max_tokens=500,
        )

    with st.spinner("📊 Identifying skill gaps..."):
        st.session_state.gaps = ask_gemini(
            f"Analyze this resume and highlight missing skills, certifications, and experiences needed for better job opportunities:\n\n{st.session_state.resume_text}",
            max_tokens=400,
        )

    with st.spinner("🚀 Creating career roadmap..."):
        st.session_state.roadmap = ask_gemini(
            f"Based on this resume, suggest a future roadmap to improve career prospects "
            f"(skills to learn, certifications needed, industry exposure):\n\n{st.session_state.resume_text}",
            max_tokens=400,
        )

    st.success("✅ Resume analysis completed successfully!")
